### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by 3kynox** [ppfeufer/aa-theme-slate#14]
### Bug Description

While executing pip install aa-theme-slate, it looks like the theme files are placed at a wrong location.

### Steps to Reproduce

1. Execute pip install aa-theme-slate
2. Modify config accordingly to the docs
3. AA page is shown without css decoration
4. Some files is returned in network tab showing few 404

### Expected behavior

The new theme should be applied.

### Screenshots

![image](https://user-images.githubusercontent.com/308755/152701370-b5c2f97f-311b-4acd-b049-d3af81a5a4cb.png)

### Please complete the following information:

- Theme Version: Latest (pip)
- Alliance Auth Version: 2.10.0
- Browser and Version: Chrome 97.0.4692.99

### Additional context

Looks like files are installed in this folder : 
/var/www/vhosts/my_user_folder/venv/auth/lib/python3.7/site-packages/aa_theme_slate-1.3.0.dist-info/*
/var/www/vhosts/my_user_folder/venv/auth/lib/python3.7/site-packages/aa_theme_slate/*
/var/www/vhosts/my_user_folder/venv/auth/lib/python3.7/site-packages/testauth/*

Instead of where my AA app is intalled:
/var/www/vhosts/my_user_folder/myauth/static/*

I rolled back for the time being byu uninstalling with pip and removed configuration of the theme from local.py

Thanks in advance

**Comment by ppfeufer** [comment]
Run 
```shell
python manage.py collectstatic
```

**Comment by 3kynox** [comment]
That should be visible I'm new to the Python world now. Thanks a lot, it works perfectly now :)
